[server]
url = "http://0.0.0.0:30080"
cert = "tls/cert.pem"
key = "tls/key.pem"
redirect-from = [
    "http://0.0.0.0:30081",
    "https://0.0.0.0:30082",
]

[log]
actix-web = "debug"
webapp = "trace"

[postgres]
host = "db"
username = "username"
password = ""
database = "database"
